#!/bin/bash

clear 

echo -e "\e[35m 




╔═╗╦ ╦╔╦╗╦ ╦╔═╗╔╗╔ 
╠═╝╚╦╝ ║ ╠═╣║ ║║║║ 
╩   ╩  ╩ ╩ ╩╚═╝╝╚╝ 
Dev :  Arturo254
╔═╗╔═╗╦═╗╦  ╦╔═╗╦═╗
╚═╗║╣ ╠╦╝╚╗╔╝║╣ ╠╦╝
╚═╝╚═╝╩╚═ ╚╝ ╚═╝╩╚═

"""



echo -e "\e[1;35m亗─────────────────────────────────────────────────────────────亗

"





echo -e "\e[1;33mINGRESA LA SIGUIENTE DIRECCION IP EN TU NAVEGADOR :"


echo -e "\e[31m "

ifconfig > /dev/null 2>&1 | grep "inet " | awk '{print $2}' | grep 192.168

echo -e "\e[34mAGREGANDO EL PUERTO : "

echo -e "\e[1;36m 8080"

echo -e "\e[35m DIRECCION ALTERNATIVA : 127.0.0.1:8080"



echo -e "\e[1;34m CONEXIONES ACTIVAS : "


python -m http.server 8080 > /dev/null 
